//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Elmo.Model
{
    /// <summary>
    /// 实体类Account。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Account")]
    [Serializable]
    public partial class Account : Entity
    {
        #region Model
		private int _AccountId;
		private int _CustomerId;
		private string _Username;
		private string _Password;
		private DateTime? _CreatedOn;
		private DateTime? _ModifiedOn;
		private int? _CreatedBy;
		private int? _Owner;
		private string _Description;
		private int _StatusCode;

		/// <summary>
		/// 
		/// </summary>
		[Field("AccountId")]
		public int AccountId
		{
			get{ return _AccountId; }
			set
			{
				this.OnPropertyValueChange("AccountId");
				this._AccountId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CustomerId")]
		public int CustomerId
		{
			get{ return _CustomerId; }
			set
			{
				this.OnPropertyValueChange("CustomerId");
				this._CustomerId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Username")]
		public string Username
		{
			get{ return _Username; }
			set
			{
				this.OnPropertyValueChange("Username");
				this._Username = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Password")]
		public string Password
		{
			get{ return _Password; }
			set
			{
				this.OnPropertyValueChange("Password");
				this._Password = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreatedOn")]
		public DateTime? CreatedOn
		{
			get{ return _CreatedOn; }
			set
			{
				this.OnPropertyValueChange("CreatedOn");
				this._CreatedOn = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ModifiedOn")]
		public DateTime? ModifiedOn
		{
			get{ return _ModifiedOn; }
			set
			{
				this.OnPropertyValueChange("ModifiedOn");
				this._ModifiedOn = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreatedBy")]
		public int? CreatedBy
		{
			get{ return _CreatedBy; }
			set
			{
				this.OnPropertyValueChange("CreatedBy");
				this._CreatedBy = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Owner")]
		public int? Owner
		{
			get{ return _Owner; }
			set
			{
				this.OnPropertyValueChange("Owner");
				this._Owner = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Description")]
		public string Description
		{
			get{ return _Description; }
			set
			{
				this.OnPropertyValueChange("Description");
				this._Description = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("StatusCode")]
		public int StatusCode
		{
			get{ return _StatusCode; }
			set
			{
				this.OnPropertyValueChange("StatusCode");
				this._StatusCode = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.AccountId,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.AccountId;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.AccountId,
				_.CustomerId,
				_.Username,
				_.Password,
				_.CreatedOn,
				_.ModifiedOn,
				_.CreatedBy,
				_.Owner,
				_.Description,
				_.StatusCode,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._AccountId,
				this._CustomerId,
				this._Username,
				this._Password,
				this._CreatedOn,
				this._ModifiedOn,
				this._CreatedBy,
				this._Owner,
				this._Description,
				this._StatusCode,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Account");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AccountId = new Field("AccountId", "Account", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CustomerId = new Field("CustomerId", "Account", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Username = new Field("Username", "Account", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Password = new Field("Password", "Account", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreatedOn = new Field("CreatedOn", "Account", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ModifiedOn = new Field("ModifiedOn", "Account", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreatedBy = new Field("CreatedBy", "Account", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Owner = new Field("Owner", "Account", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Description = new Field("Description", "Account", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field StatusCode = new Field("StatusCode", "Account", "");
        }
        #endregion
	}
}