//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Elmo.Model
{
    /// <summary>
    /// 实体类Customer。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Customer")]
    [Serializable]
    public partial class Customer : Entity
    {
        #region Model
		private int _CustomerId;
		private string _Name;
		private int? _Gender;
		private int? _Age;
		private DateTime? _Birthday;
		private int? _City;
		private bool _IsVIP;
		private DateTime? _CreatedOn;
		private DateTime? _ModifiedOn;
		private int? _CreatedBy;
		private int? _Owner;
		private string _Description;
		private int _StatusCode;

		/// <summary>
		/// 
		/// </summary>
		[Field("CustomerId")]
		public int CustomerId
		{
			get{ return _CustomerId; }
			set
			{
				this.OnPropertyValueChange("CustomerId");
				this._CustomerId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Name")]
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange("Name");
				this._Name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Gender")]
		public int? Gender
		{
			get{ return _Gender; }
			set
			{
				this.OnPropertyValueChange("Gender");
				this._Gender = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Age")]
		public int? Age
		{
			get{ return _Age; }
			set
			{
				this.OnPropertyValueChange("Age");
				this._Age = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Birthday")]
		public DateTime? Birthday
		{
			get{ return _Birthday; }
			set
			{
				this.OnPropertyValueChange("Birthday");
				this._Birthday = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("City")]
		public int? City
		{
			get{ return _City; }
			set
			{
				this.OnPropertyValueChange("City");
				this._City = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("IsVIP")]
		public bool IsVIP
		{
			get{ return _IsVIP; }
			set
			{
				this.OnPropertyValueChange("IsVIP");
				this._IsVIP = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreatedOn")]
		public DateTime? CreatedOn
		{
			get{ return _CreatedOn; }
			set
			{
				this.OnPropertyValueChange("CreatedOn");
				this._CreatedOn = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ModifiedOn")]
		public DateTime? ModifiedOn
		{
			get{ return _ModifiedOn; }
			set
			{
				this.OnPropertyValueChange("ModifiedOn");
				this._ModifiedOn = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreatedBy")]
		public int? CreatedBy
		{
			get{ return _CreatedBy; }
			set
			{
				this.OnPropertyValueChange("CreatedBy");
				this._CreatedBy = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Owner")]
		public int? Owner
		{
			get{ return _Owner; }
			set
			{
				this.OnPropertyValueChange("Owner");
				this._Owner = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Description")]
		public string Description
		{
			get{ return _Description; }
			set
			{
				this.OnPropertyValueChange("Description");
				this._Description = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("StatusCode")]
		public int StatusCode
		{
			get{ return _StatusCode; }
			set
			{
				this.OnPropertyValueChange("StatusCode");
				this._StatusCode = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.CustomerId,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.CustomerId;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.CustomerId,
				_.Name,
				_.Gender,
				_.Age,
				_.Birthday,
				_.City,
				_.IsVIP,
				_.CreatedOn,
				_.ModifiedOn,
				_.CreatedBy,
				_.Owner,
				_.Description,
				_.StatusCode,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._CustomerId,
				this._Name,
				this._Gender,
				this._Age,
				this._Birthday,
				this._City,
				this._IsVIP,
				this._CreatedOn,
				this._ModifiedOn,
				this._CreatedBy,
				this._Owner,
				this._Description,
				this._StatusCode,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Customer");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CustomerId = new Field("CustomerId", "Customer", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name", "Customer", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Gender = new Field("Gender", "Customer", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Age = new Field("Age", "Customer", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Birthday = new Field("Birthday", "Customer", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field City = new Field("City", "Customer", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field IsVIP = new Field("IsVIP", "Customer", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreatedOn = new Field("CreatedOn", "Customer", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ModifiedOn = new Field("ModifiedOn", "Customer", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreatedBy = new Field("CreatedBy", "Customer", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Owner = new Field("Owner", "Customer", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Description = new Field("Description", "Customer", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field StatusCode = new Field("StatusCode", "Customer", "");
        }
        #endregion
	}
}