//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Elmo.Model
{
    /// <summary>
    /// 实体类Order。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Order")]
    [Serializable]
    public partial class Order : Entity
    {
        #region Model
		private int _OrderId;
		private string _Code;
		private float? _TotalPrice;
		private float? _DeliveryFee;
		private float? _Discounts;
		private bool? _InvoiceTake;
		private int _CustomerId;

		/// <summary>
		/// 
		/// </summary>
		[Field("OrderId")]
		public int OrderId
		{
			get{ return _OrderId; }
			set
			{
				this.OnPropertyValueChange("OrderId");
				this._OrderId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Code")]
		public string Code
		{
			get{ return _Code; }
			set
			{
				this.OnPropertyValueChange("Code");
				this._Code = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TotalPrice")]
		public float? TotalPrice
		{
			get{ return _TotalPrice; }
			set
			{
				this.OnPropertyValueChange("TotalPrice");
				this._TotalPrice = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeliveryFee")]
		public float? DeliveryFee
		{
			get{ return _DeliveryFee; }
			set
			{
				this.OnPropertyValueChange("DeliveryFee");
				this._DeliveryFee = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Discounts")]
		public float? Discounts
		{
			get{ return _Discounts; }
			set
			{
				this.OnPropertyValueChange("Discounts");
				this._Discounts = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("InvoiceTake")]
		public bool? InvoiceTake
		{
			get{ return _InvoiceTake; }
			set
			{
				this.OnPropertyValueChange("InvoiceTake");
				this._InvoiceTake = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CustomerId")]
		public int CustomerId
		{
			get{ return _CustomerId; }
			set
			{
				this.OnPropertyValueChange("CustomerId");
				this._CustomerId = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.OrderId,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.OrderId,
				_.Code,
				_.TotalPrice,
				_.DeliveryFee,
				_.Discounts,
				_.InvoiceTake,
				_.CustomerId,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._OrderId,
				this._Code,
				this._TotalPrice,
				this._DeliveryFee,
				this._Discounts,
				this._InvoiceTake,
				this._CustomerId,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Order");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field OrderId = new Field("OrderId", "Order", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Code = new Field("Code", "Order", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TotalPrice = new Field("TotalPrice", "Order", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeliveryFee = new Field("DeliveryFee", "Order", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Discounts = new Field("Discounts", "Order", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field InvoiceTake = new Field("InvoiceTake", "Order", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CustomerId = new Field("CustomerId", "Order", "");
        }
        #endregion
	}
}